Class {
	#name : #RTSourceCodeSolidityDictionary,
	#superclass : #RTNameCloudDictionary,
	#category : #MiningSolidity
}

{ #category : #hooks }
RTSourceCodeSolidityDictionary >> unnecessaryWords [
	^ #('solidity' 'ethereum' 'contract' 'contracts' 'for' 'in' 'of' 'to' 'its' 'i' 'the' 'smart' 'on' 'a' 'is' 'this' 'or' 'it' 'smartcontract' 'smartcontracts''my' 'be' 'at' 'as' 'de' 'and' 'can' 'by' 'with' 'none')
]
